export interface Consultation {
  patientId: any;
  id?: string;
  cpf: string;
  nomePaciente: string;
  dataConsulta: string;
  horaConsulta: string;
  duracaoConsulta: number;
  tipoConsulta: string;
  especialidade: string;
  profissional: string;
  motivoConsulta: string;
  sintomasRelatados?: string;
  statusConsulta: 'Agendada' | 'Confirmada' | 'EmAndamento' | 'Concluida' | 'Cancelada' | 'Remarcada';
  prioridade: 'Baixa' | 'Media' | 'Alta' | 'Urgente';
  ultimaGlicemia?: string;
  ultimaHemoglobina?: string;
  medicamentos?: string;
  alergias?: string;
  precisaAcompanhante: boolean;
  nomeAcompanhante?: string;
  telefoneAcompanhante?: string;
  salaAtendimento?: string;
  consultaRemota: boolean;
  linkConsultaRemota?: string;
  enviarLembreteEmail: boolean;
  enviarLembreteSMS: boolean;
  observacoes?: string;
  email: string;
  createdAt?: string;
  updatedAt?: string;
}